###
# About/contact for the site author
#
# name of the author of the site
name = "Sean Kearney"

# description to display in the sidebar
description = "A passionate <span class=\"codinfox-changing-keywords\"><b class=\"visible\">developer,</b><b class=\"hidden\">technologist,</b></span> lead by curiosity."

# the profile image of the author to display in the sidebar
gravatar = "180c1b0844c902abbfef963baa491b94" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "github", path = "https://github.com/seankearney" },
  { name = "stack-overflow", path = "https://stackoverflow.com/users/255194/sean-kearney" },
  { name = "twitter", path = "https://twitter.com/seankearney" },
  { name = "linkedin", path = "https://www.linkedin.com/in/skearney/" }
]
