[[nav]]
name = "Home"
path = "/"

[[nav]]
name = "Categories"
path = "/tags/"

[[nav]]
name = "Archive"
path = "/archive/"

[[nav]]
name = "About"
path = "/about/"

[[nav]]
name = "Feed"
path = "/rss.xml"